import pytest #noqa
import networkx as nx
from hypothesis import given, strategies as st
from pydescope.graph_builder import GraphBuilder

# Strategy to generate a list of edges: tuples of (source_node, target_node)
# Each node string will have a length between 1 and 15 characters
edge_strategy = st.lists(
    st.tuples(
        st.text(min_size=1, max_size=15), 
        st.text(min_size=1, max_size=15)
    ),
    min_size=0,
    max_size=30
)

@given(edge_strategy)
def test_graph_generation_with_arbitrary_edges(edges):
    """Verify DiGraph generation and edge counts using arbitrary node pairs."""
    
    # Pass the generated edges into the constructor as required
    builder = GraphBuilder(edges=edges)
    
    # Build the NetworkX graph
    graph = builder.build()
    
    # Assertions to ensure integrity
    assert isinstance(graph, nx.DiGraph)
    
    # The number of edges in the networkx graph should match 
    # the number of unique edges generated by hypothesis
    assert graph.number_of_edges() == len(set(edges))